### ISSUE TITLE
AWS - ECR policy issue  for some accounts

### ISSUE THREAD

**Issue by lohithkc** [cloudposse/terraform-aws-ecr#8]
For certain users,  AWS is not allowing restricting the ECR read for specific resource. The policy can  be updated to all `[*]` resources only.

```
data "aws_iam_policy_document" "token" {
  statement {
    sid     = "ECRGetAuthorizationToken"
    effect  = "Allow"
    actions = ["ecr:GetAuthorizationToken"]

    resources = ["*"]   //it's working
    //resources = ["${aws_ecr_repository.default.arn}"]  --> not working 

  }
}
```

**Comment by aknysh** [comment]
@lohithkc 
thank you for testing and submitting the issue.
we'll review it and get back to you

**Comment by aknysh** [comment]
@lohithkc 
We found that the issue was caused by potential data races due to circular dependencies in the module.
Although we did not see it in our deployments, it probably depends on many factors (e.g. `Terraform` version, AWS region, how many other resources are created at the same time, how the module is used with other modules, etc.).
We applied the fix here https://github.com/cloudposse/terraform-aws-ecr/releases/tag/0.2.5
Thanks again for testing.
